# environment.yml

name: readthedocs # this is just a name for the environment
dependencies:
  - sphinx_rtd_theme
  - python=3.5
  - pyqt=4
  - numpy
  - pip:
      - sphinx
      - recommonmark
      - https://bitbucket.org/fchampalimaud/logging-bootstrap/get/master.zip